version: "3"
services:
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3333:3333
    environment:
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
    volumes:
      - ./src:/app/src
